name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  deploy-coverage-report:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' # Only run on pushes to main
    permissions:
      contents: write # Allow GITHUB_TOKEN to write to gh-pages branch
    steps:
      - name: Download coverage report artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage # Download to a directory named 'coverage'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage/lcov-report # Directory containing HTML files
          # Optional: keep_files: true # To keep old files on gh-pages branch
          # Optional: cname: your.custom.domain # If you have a custom domain
